title: Sam Craig
description: Sam Craig's personal website
cssurl: "/assets/css"
imgurl: "/assets/img"
url: "http://sammidysam.github.io/"

# Not sure if this is working.
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
